//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpchainWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_menu()
        {
            this.tbl_chitiethoadon = new HashSet<tbl_chitiethoadon>();
            this.tbl_chitiethoadonnhap = new HashSet<tbl_chitiethoadonnhap>();
        }
    
        public int iMaSP { get; set; }
        public string sTenSP { get; set; }
        public Nullable<int> iDonGia { get; set; }
        public Nullable<int> iMaLoaiSP { get; set; }
        public string sDonViTinh { get; set; }
        public Nullable<int> iSoLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_chitiethoadon> tbl_chitiethoadon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_chitiethoadonnhap> tbl_chitiethoadonnhap { get; set; }
        public virtual tbl_loaisp tbl_loaisp { get; set; }
    }
}
