//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpchainWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_khuyenmai
    {
        public int id { get; set; }
        public Nullable<int> idMatHang { get; set; }
        public Nullable<int> tiLe { get; set; }
        public Nullable<System.DateTime> thoiGianBatDau { get; set; }
        public Nullable<System.DateTime> thoiGianKetThuc { get; set; }
    }
}
