//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpchainWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ban()
        {
            this.tbl_hoadon_tam = new HashSet<tbl_hoadon_tam>();
        }
    
        public int iMaBan { get; set; }
        public string sTenBan { get; set; }
        public Nullable<byte> iTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hoadon_tam> tbl_hoadon_tam { get; set; }
    }
}
