//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpchainWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_taikhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_taikhoan()
        {
            this.tbl_hoadon = new HashSet<tbl_hoadon>();
            this.tbl_hoadonnhap = new HashSet<tbl_hoadonnhap>();
        }
    
        public int id { get; set; }
        public string sTenDangNhap { get; set; }
        public string sMatKhau { get; set; }
        public string sTenNguoiDung { get; set; }
        public Nullable<byte> iGioiTinh { get; set; }
        public string sSDT { get; set; }
        public string sDiaChi { get; set; }
        public Nullable<int> iPhanQuyen { get; set; }
        public Nullable<byte> iTrangThai { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
        public string cmnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hoadon> tbl_hoadon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hoadonnhap> tbl_hoadonnhap { get; set; }
        public virtual tbl_phanquyen tbl_phanquyen { get; set; }
    }
}
