//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpchainWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hoadon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_hoadon()
        {
            this.tbl_chitiethoadon = new HashSet<tbl_chitiethoadon>();
        }
    
        public int imaHD { get; set; }
        public Nullable<int> iMaNguoiLap { get; set; }
        public Nullable<System.DateTime> dThoiGianLap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_chitiethoadon> tbl_chitiethoadon { get; set; }
        public virtual tbl_taikhoan tbl_taikhoan { get; set; }
    }
}
