//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpchainWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hoadon_tam
    {
        public int ID { get; set; }
        public Nullable<int> iMaHD { get; set; }
        public Nullable<int> iMaBan { get; set; }
        public Nullable<int> iMaNV { get; set; }
        public int iMaSP { get; set; }
        public Nullable<int> iSoluong { get; set; }
        public Nullable<int> iTrangThai { get; set; }
    
        public virtual tbl_ban tbl_ban { get; set; }
    }
}
